name: Build and Push to ECR

on:
  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-push-service1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251701672:role/s3-github
          role-session-name: github-assume
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image for Service1
        run: |
          docker build -t 650251701672.dkr.ecr.us-east-1.amazonaws.com/test-repo-1:${{ github.sha }} ./docker/appointments

      - name: Push Docker Image for Service1
        run: |
          docker push 650251701672.dkr.ecr.us-east-1.amazonaws.com/test-repo-1:${{ github.sha }}

      - name: Save Service1 Image Tag
        run: echo "SERVICE1_IMAGE=650251701672.dkr.ecr.us-east-1.amazonaws.com/test-repo-1:${{ github.sha }}" >> $GITHUB_ENV

  build-push-service2:
    runs-on: ubuntu-latest
    needs: build-push-service1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251701672:role/s3-github
          role-session-name: github-assume
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image for Service2
        run: |
          docker build -t 650251701672.dkr.ecr.us-east-1.amazonaws.com/test-repo-2:${{ github.sha }} ./docker/patient

      - name: Push Docker Image for Service2
        run: |
          docker push 650251701672.dkr.ecr.us-east-1.amazonaws.com/test-repo-2:${{ github.sha }}

      - name: Save Service2 Image Tag
        run: echo "SERVICE2_IMAGE=650251701672.dkr.ecr.us-east-1.amazonaws.com/test-repo-2:${{ github.sha }}" >> $GITHUB_ENV
